# Caddy with forward_proxy plugin for NaiveProxy server
FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
